spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
logging.level.org.springframework.web.client.RestTemplate=DEBUG
#logging.level.org.apache.http=DEBUG
#logging.level.httpclient.wire=DEBUG
server.port=8080
logging.level.org.springframework.boot.autoconfigure=DEBUG
shareit-server.url=http://localhost:9090